routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| These routes point to the public pages of the application. No 
| middleware is assigned to them as a result
|
*/

Route::namespace('Frontend')->group(function () {
	Route::get('/', 'PageController@getWelcome');
	Route::get('/documentation', 'PageController@getDocs');
	Route::get('complete-registration', 'PageController@getCompleteRegistration')->name('registration.complete');
	Route::get('login-and-signup-procedure', 'PageController@getHowTo')->name('howto');
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| These routes point to the private pages of the application. Some 
| middleware is assigned to them as a result.
|
*/

Route::namespace('Backend')->group(function () {
	Route::get('/dashboard', 'PageController@getDashboard')->name('dashboard');
	Route::get('ussd-static', 'PageController@getStaticUSSD')->name('ussd.static');
	Route::get('ussd-dynamic', 'PageController@getDynamicUSSD')->name('ussd.dynamic');
	Route::get('sms-static', 'PageController@getStaticSMS')->name('sms.static');
	Route::get('sms-dynamic', 'PageController@getDynamicSMS')->name('sms.dynamic');
	Route::get('shortcode-details', 'PageController@getShortcodeDetails')->name('details.shortcode');
	Route::resource('users', 'UserController');
	Route::get('verified', 'UserController@verified')->name('verified');
	Route::get('unverified', 'UserController@unverified')->name('unverified');
	Route::get('active', 'UserController@active')->name('active');
	Route::get('inactive', 'UserController@inactive')->name('inactive');
	Route::get('change-role/{id}', 'UserController@getChangeRole')->name('user.role');
	Route::post('change-role/{id}', 'UserController@postChangeRole')->name('role.change');
	Route::post('deactivate-user/{id}', 'UserController@deactivate')->name('user.deactivate');
	Route::post('activate-user/{id}', 'UserController@activate')->name('user.activate');
	Route::get('profile', 'PageController@getProfile')->name('user.profile');
	Route::post('change-avatar', 'PageController@postChangeAvatar')->name('avatar.change');
	Route::post('edit-details', 'PageController@postChangeDetails')->name('profile.update');
	Route::resource('roles', 'RoleController');
	Route::get('attach-permission/{id}', 'RoleController@getChangePermission')->name('role.permission');
	Route::post('attach-permission/{id}', 'RoleController@postChangePermission')->name('permission.change');
	Route::resource('permissions', 'PermissionController');
	Route::get('analytics-graphs', 'ReportController@getGraphs')->name('analytics.graphs');
	Route::get('analytics-reports', 'ReportController@getReports')->name('analytics.reports');
	Route::resource('companies', 'CompanyController');
	Route::post('activate-company/{id}', 'CompanyController@activateCompany')->name('company.activate');
	Route::post('deactivate-company/{id}', 'CompanyController@deactivateCompany')->name('company.deactivate');
	//Route::get('company-users', 'CompanyController@users')->name('company.users');
	Route::get('manage-company', 'CompanyController@manageCompany')->name('company.manage');
    Route::post('/createtrivia','GamesController@addtrivia')->name('trivia.create');
    Route::post('/addquestions','GamesController@addtriviaquestions')->name('trivia.addquestions');
    Route::get('/deletetrivia','GamesController@deletetrivia')->name('trivia.delete');
    Route::get('/marketing/email','MarketingController@emailMarketing')->name('marketingemail.send');
    Route::post('/marketing/email', 'MarketingController@postSendEmail')->name('marketingemail.bulksend');
	Route::get('marketing/email-groups', 'MarketingController@emailGroups')->name('marketingemail.groups');
	Route::get('marketing/view-email-group/{id}', 'MarketingController@showEmailGroup')->name('marketingemail.showgroup');
	Route::get('marketing/edit-email-group/{id}', 'MarketingController@editEmailGroup')->name('marketingemail.editgroup');
	Route::post('marketing/update-email-group/{id}', 'MarketingController@updateEmailGroup')->name('marketingemail.updategroup');
	Route::get('/marketing/view-email-contact/{id}','MarketingController@showEmailContact')->name('marketingemail.emailcontact');
	Route::post('add-email-group', 'MarketingController@addEmailGroup')->name('emailgroup.add');
	Route::post('add-email-contact/{id}', 'MarketingController@addEmailContact')->name('emailcontact.add');
	Route::get('marketing/sms', 'MarketingController@smsMarketing')->name('marketingsms.send');
	Route::get('marketing/sms-groups', 'MarketingController@smsGroups')->name('marketingsms.groups');
	Route::get('marketing/view-sms-group', 'MarketingController@showSMSGroup')->name('marketingsms.showgroup');
	Route::get('marketing/edit-sms-group', 'MarketingController@editSMSGroup')->name('marketingsms.editgroup');
	Route::get('/marketing/view-sms-contact','MarketingController@showSMSContact')->name('marketingsms.smscontact');
});

Route::get('/trivia','GamesManagementController@trivia');

Route::get('/listtrivia','GamesManagementController@listtrivia');
Route::get('/viewtrivia','GamesManagementController@viewtrivia');
Route::get('players','GamesManagementController@getPlayers');
Route::get('player-details', 'GamesManagementController@getPlayerDetails');
Route::get('/polls','GamesManagementController@polls')->name('polls');
Route::post('/create_polls','Backend\ElectionsController@create');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('/polls','GamesManagementController@polls');
Route::get('edit-poll', 'GamesManagementController@editPoll');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('lifestyle-types', 'GamesManagementController@getLifestyleTypes')->name('lifestyle.types');
Route::get('edit-lifestyle', 'GamesManagementController@editLifestyleType')->name('lifestyle.edit');
Route::get('create-lifestyle', 'GamesManagementController@createLifestyle')->name('lifestyle.create');
Route::get('games-present', 'GamesManagementController@lifestyleGamesPresent')->name('lifestylegames.index');
Route::get('create-lifestyle-game', 'GamesManagementController@createLifestyleGame')->name('lifestylegames.create');
Route::get('edit-lifestyle-game', 'GamesManagementController@editLifestyleGame')->name('lifestylegames.edit');
Route::get('view-lifestyle-game', 'GamesManagementController@showLifestyleGame')->name('lifestylegames.show');
 
//Route::get('/lifestyle','GamesManagementController@lifestyle');
Route::get('/lottery','GamesManagementController@lottery');
Route::get('/marketting','GamesManagementController@marketting');
Route::get('listpolls', 'Backend\ElectionsController@view');
Route::get('poll-details', 'Backend\ElectionsController@getinvidualpoll')->name("polls.details");
Route::get('poll-participants', 'Backend\ElectionsController@getparticipants')->name("polls.participants");
Route::get('listpolls', 'GamesManagementController@getAllPolls');
Route::get('poll-details', 'GamesManagementController@getPollDetails');
Route::post('/postemails','API\MarketingController@postemails');
Route::post('/postsms','API\MarketingController@postsms');
Route::post('createproject', 'API\ProjectsController@createproject');
Route::get('getprojects', 'API\ProjectsController@getprojects');
Route::get('getdetails', 'API\ProjectsController@getprojectsdetails');
Route::get('getstatistics', 'API\UssdController@getstatistics');
Route::get('getsessions', 'API\UssdController@getsessions');
Route::get('getsmstype', 'API\ProjectsController@getsmstype');
Route::get('getstatisticsms', 'API\SmsController@getstatistics');
Route::get('getoutgoing', 'API\SmsController@getoutgoing');
Route::get('getincomingsms', 'API\SmsController@getincomingsms');


/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| These routes deal with all authentication logic of the app. 
|
*/

Auth::routes();
Route::namespace('Auth')->group(function () {
	Route::get('register/verify/{token}', 'RegisterController@verifyEmail');
	Route::post('complete-registration', 'RegisterController@completeRegistration')->name('reg.complete');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    //
}

app/Http/Controllers/Backend/RoleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Role;
use App\Permission;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::orderBy('id', 'asc')->paginate(10);
        return view('backend/modules/role/index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        return view('backend/modules/role/create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:15|unique:roles,name',
            'display_name' => 'required|min:5|max:30',
            'description' => 'required|min:5|max:255'
        ]);

        $role = new Role;
        $role->name = $request->name;
        $role->display_name = $request->display_name;
        $role->description = $request->description;
        $role->save();

       if ($request->permissions) {
           $role->attachPermissions($request->permissions);
       }

       Session::flash('new-role', 'You have successfully created the '. $role->name . ' role');
       return redirect()->route('roles.show', $role->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::findOrFail($id);
        $users = $role->users()->paginate(10);
        return view('backend/modules/role/show', compact('role', 'users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::where('id', $id)->with('permissions')->first();
        $permissions = Permission::all();
        $role_permissions = $role->permissions()->pluck('id','id')->toArray();
        return view('backend/modules/role/edit', compact('role', 'permissions', 'role_permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        
        $this->validate($request, [
            'name' => [
                'required', 'max:15', 
                Rule::unique('roles')->ignore($role->id),
            ],
            'display_name' => 'required|min:5|max:30',
            'description' => 'required|min:5|max:255'
        ]);

        $role->name = $request->name;
        $role->display_name = $request->display_name;
        $role->description = $request->description;
        $role->save();

        DB::table('permission_role')->where('role_id',$id)->delete(); // Delete the permission relationships first and then save

        if ($request->permissions) {
           $role->attachPermissions($request->permissions);
        }
        
        Session::flash('update-role', 'You have successfully updated the '. $role->name . ' role');
        return redirect()->route('roles.show', $id);
    }

    /**
     * Display the form for attaching permissions.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getChangePermission($id)
    {
        $role = Role::where('id', '=', $id)->first();
        $permissions = Permission::all();
        $role_permissions = $role->permissions()->pluck('id', 'id')->toArray();
        return view('backend/modules/role/attach-permission', compact('role', 'permissions', 'role_permissions'));
    }

    /**
     * Attach permissions to the retrieved role.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function postChangePermission(Request $request, $id)
    {
        $role = Role::find($id);
        DB::table('permission_role')->where('role_id', $id)->delete();

        if($request->permissions) {
            $role->attachPermissions($request->permissions);
        }

        Session::flash('role-permission', 'Permissions belonging to ' . $role->name . ' have been successfully updated');
        return redirect()->route('roles.show', $role->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id); // Pull back a given role
        // Regular Delete
        $role->delete(); // This will work no matter what

        Session::flash('delete-role', 'The role has been deleted successfully');
        return redirect()->route('roles.index');
    }
}

resources/views/backend/modules/role/create.blade.php
@extends('backend/layouts/template')

@section('title')
	Create Role
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Create Role</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li>
                    <a href="{{ route('roles.index') }}">Roles</a>
                </li>
                <li>
                    <strong>Create role</strong>
                </li>

            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="ibox-float-e-margins">
                <div class="ibox-title">
                    <h5>Create new role</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r">
                            <form action="{{ route('roles.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label>Name</label> 
                                    <input type="text" placeholder="eg admin" id="name" name="name" class="form-control">
                                    <!-- If name has error -->
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                                    <label>Display Name</label> 
                                    <input type="text" placeholder="eg Administrator" id="display_name" name="display_name" class="form-control">
                                    <!-- If display name has error -->
                                    @if ($errors->has('display_name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('display_name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                    <label>Description</label> 
                                    <input type="description" placeholder="eg Has access to dashboard" id="description" name="description" class="form-control">
                                    <!-- If description has error -->
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="roles">Permissions</label>
                                    <div class="row checkbox i-checks">
                                        @if(count($permissions) > 0)
                                            @foreach($permissions->chunk(3) as $chunk)
                                                @foreach($chunk as $permission)
                                                    <div class="col-xs-4">
                                                        <input type="checkbox" name="permissions[]" value="{{ $permission->id }}"> {{ $permission->name }}
                                                    </div>
                                                @endforeach
                                            @endforeach
                                        @else
                                            <div class="col-xs-12">
                                                <div class="alert alert-warning">
                                                    No permissions have been created yet.
                                                </div>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
@endsection

resources/views/backend/modules/role/index.blade.php
@extends('backend/layouts/template')

@section('title')
	All Roles
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>All Roles</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li class="active">
                    <strong>Roles</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-float e-margins">
                <div class="ibox-title">
                    <h5>All roles in {{ config('app.name') }}</h5>
                    <div class="ibox-tools"> 
                        <a href="{{ route('roles.create') }}" class="btn btn-primary btn-sm">New Role</a>
                    </div>
                </div>
            </div>

            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover users-table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Display Name</th>
                                <th>Description</th>
                                <th>Users</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($roles) > 0)
                                @foreach($roles as $role)
                                    <tr>
                                        <td>{{ $role->name }}</td>
                                        <td>{{ $role->display_name }}</td>
                                        <td>{{ substr(strip_tags($role->description), 0, 40) }}{{ strlen(strip_tags($role->description)) > 40 ? "..." : "" }}</td>
                                        <td>{{ count($role->users) }}</td>
                                        <td>
                                            {{ date('M j, Y', strtotime($role->created_at)) . ' at ' . date('H:i', strtotime($role->created_at)) }}
                                        </td>
                                        <td>
                                            <a href="{{ route('roles.show', $role->id) }}" class="btn btn-xs btn-primary" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                            <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-xs btn-success" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                            {!! Form::open(['route' => ['roles.destroy', $role->id], 'method' => 'DELETE', 'style' => 'display: inline-block']) !!}                                
                                               {{Form::button('<i class="fa fa-trash"></i>', array('type' => 'submit', 'class' => 'btn btn-xs btn-danger', 'title' => 'Delete'))}}
                                            {!! Form::close() !!} &nbsp;&nbsp;
                                            <a href="{{ route('role.permission', $role->id) }}" class="btn btn-xs btn-info" title="Attach Permission"><i class="fa fa-unlock-alt" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6" class="alert alert-warning text-center">No roles are available at the moment</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                    @if(count($roles) > 0)
                        <div>
                            <span style="line-height: 60px;">Showing {!! $roles->firstItem() !!} to {!! $roles->lastItem() !!} of {{ $roles->total() }} roles</span>
                            <span class="pull-right">{!! $roles->links(); !!}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/role/show.blade.php
@extends('backend/layouts/template')

@section('title')
	View Role
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>View Role</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li>
                    <a href="{{ route('roles.index') }}">Roles</a>
                </li>
                <li>
                    <strong>View {{ $role->name }}</strong>
                </li>

            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
	<div class="row">
		<div class="col-sm-4">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>About {{ ucfirst($role->name) }} role</h5>
                </div>
                <div class="ibox-content profile-content">
                    <h5>
                        <i class="fa fa-lock" style="color: #1BB394"></i> Permissions
                    </h5>
                    <p>
                       @if(count($role->permissions) > 0)
							@foreach($role->permissions as $permission)
	                           <span class="label label-default" style="display: inline-block; margin-bottom: 3px;">{{ $permission->name }}</span>
	                       @endforeach
                       @else
							<span class="">No permissions assigned</span>
                       @endif
                    </p>
                    <div class="row m-t-lg">
                        <div class="col-md-4">
                            <i class="fa fa-user" style="color: #1BB394"></i>
                            <h5><strong>{{ count($role->users) }}</strong> users have this role</h5>
                        </div>
                        <div class="col-md-4">
                            <i class="fa fa-calendar" style="color: #1BB394"></i>
                            <h5>Created on <strong>{{ date('M j, Y', strtotime($role->created_at)) }}</strong></h5>
                        </div>
                        <div class="col-md-4">
                            <i class="fa fa-pencil" style="color: #1BB394"></i>
                            <h5>Last Updated <strong>{{ date('M j, Y', strtotime($role->updated_at)) }}</strong></h5>
                        </div>
                    </div>
                    <div class="user-button">
                        <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-primary btn-sm btn-block"><i class="fa fa-pencil"></i> Edit Role</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Users with this role</h5>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Email Verified</th>
                                    <th>Active</th>
                                    <th>View User</th>
                                </tr>
                            </thead>
                            @if(count($users) > 0)
                                <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>
												@if($user->verified)
													<span class="label label-primary">Yes</span>
												@else
													<span class="label label-danger">No</span>
												@endif
											</td>
											<td>
												@if($user->active)
													<span class="label label-primary">Active</span>
												@else
													<span class="label label-danger">Not Active</span>
												@endif
											</td>
                                            <td class="text-center"><a href="{{ route('users.show', $user->id) }}" class="btn btn-xs btn-primary" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp; &nbsp;</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            @else
                                <tbody>
                                    <tr>
                                        <td colspan="5" class="alert alert-warning text-center">No users assigned to this role</td>
                                    </tr>
                                </tbody>
                            @endif
                        </table>
                        @if(count($users) > 0)
                            <div>
                                <span style="line-height: 60px;">Showing {!! $users->firstItem() !!} to {!! $users->lastItem() !!} of {{ $users->total() }} users</span>
                                <span class="pull-right">{!! $users->links(); !!}</span>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>  
	</div>
@endsection