routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| These routes point to the public pages of the application. No 
| middleware is assigned to them as a result
|
*/

Route::namespace('Frontend')->group(function () {
	Route::get('/', 'PageController@getWelcome');
	Route::get('/documentation', 'PageController@getDocs');
	Route::get('complete-registration', 'PageController@getCompleteRegistration')->name('registration.complete');
	Route::get('login-and-signup-procedure', 'PageController@getHowTo')->name('howto');
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| These routes point to the private pages of the application. Some 
| middleware is assigned to them as a result.
|
*/

Route::namespace('Backend')->group(function () {
	Route::get('/dashboard', 'PageController@getDashboard')->name('dashboard');
	Route::get('ussd-static', 'PageController@getStaticUSSD')->name('ussd.static');
	Route::get('ussd-dynamic', 'PageController@getDynamicUSSD')->name('ussd.dynamic');
	Route::get('sms-static', 'PageController@getStaticSMS')->name('sms.static');
	Route::get('sms-dynamic', 'PageController@getDynamicSMS')->name('sms.dynamic');
	Route::get('shortcode-details', 'PageController@getShortcodeDetails')->name('details.shortcode');
	Route::resource('users', 'UserController');
	Route::get('verified', 'UserController@verified')->name('verified');
	Route::get('unverified', 'UserController@unverified')->name('unverified');
	Route::get('active', 'UserController@active')->name('active');
	Route::get('inactive', 'UserController@inactive')->name('inactive');
	Route::get('change-role/{id}', 'UserController@getChangeRole')->name('user.role');
	Route::post('change-role/{id}', 'UserController@postChangeRole')->name('role.change');
	Route::post('deactivate-user/{id}', 'UserController@deactivate')->name('user.deactivate');
	Route::post('activate-user/{id}', 'UserController@activate')->name('user.activate');
	Route::get('profile', 'PageController@getProfile')->name('user.profile');
	Route::post('change-avatar', 'PageController@postChangeAvatar')->name('avatar.change');
	Route::post('edit-details', 'PageController@postChangeDetails')->name('profile.update');
	Route::resource('roles', 'RoleController');
	Route::get('attach-permission/{id}', 'RoleController@getChangePermission')->name('role.permission');
	Route::post('attach-permission/{id}', 'RoleController@postChangePermission')->name('permission.change');
	Route::resource('permissions', 'PermissionController');
	Route::get('analytics-graphs', 'ReportController@getGraphs')->name('analytics.graphs');
	Route::get('analytics-reports', 'ReportController@getReports')->name('analytics.reports');
	Route::resource('companies', 'CompanyController');
	Route::post('activate-company/{id}', 'CompanyController@activateCompany')->name('company.activate');
	Route::post('deactivate-company/{id}', 'CompanyController@deactivateCompany')->name('company.deactivate');
	//Route::get('company-users', 'CompanyController@users')->name('company.users');
	Route::get('manage-company', 'CompanyController@manageCompany')->name('company.manage');
    Route::post('/createtrivia','GamesController@addtrivia')->name('trivia.create');
    Route::post('/addquestions','GamesController@addtriviaquestions')->name('trivia.addquestions');
    Route::get('/deletetrivia','GamesController@deletetrivia')->name('trivia.delete');
    Route::get('/marketing/email','MarketingController@emailMarketing')->name('marketingemail.send');
    Route::post('/marketing/email', 'MarketingController@postSendEmail')->name('marketingemail.bulksend');
	Route::get('marketing/email-groups', 'MarketingController@emailGroups')->name('marketingemail.groups');
	Route::get('marketing/view-email-group/{id}', 'MarketingController@showEmailGroup')->name('marketingemail.showgroup');
	Route::get('marketing/edit-email-group/{id}', 'MarketingController@editEmailGroup')->name('marketingemail.editgroup');
	Route::post('marketing/update-email-group/{id}', 'MarketingController@updateEmailGroup')->name('marketingemail.updategroup');
	Route::get('/marketing/view-email-contact/{id}','MarketingController@showEmailContact')->name('marketingemail.emailcontact');
	Route::post('add-email-group', 'MarketingController@addEmailGroup')->name('emailgroup.add');
	Route::post('add-email-contact/{id}', 'MarketingController@addEmailContact')->name('emailcontact.add');
	Route::get('marketing/sms', 'MarketingController@smsMarketing')->name('marketingsms.send');
	Route::get('marketing/sms-groups', 'MarketingController@smsGroups')->name('marketingsms.groups');
	Route::get('marketing/view-sms-group', 'MarketingController@showSMSGroup')->name('marketingsms.showgroup');
	Route::get('marketing/edit-sms-group', 'MarketingController@editSMSGroup')->name('marketingsms.editgroup');
	Route::get('/marketing/view-sms-contact','MarketingController@showSMSContact')->name('marketingsms.smscontact');
});

Route::get('/trivia','GamesManagementController@trivia');

Route::get('/listtrivia','GamesManagementController@listtrivia');
Route::get('/viewtrivia','GamesManagementController@viewtrivia');
Route::get('players','GamesManagementController@getPlayers');
Route::get('player-details', 'GamesManagementController@getPlayerDetails');
Route::get('/polls','GamesManagementController@polls')->name('polls');
Route::post('/create_polls','Backend\ElectionsController@create');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('/polls','GamesManagementController@polls');
Route::get('edit-poll', 'GamesManagementController@editPoll');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('lifestyle-types', 'GamesManagementController@getLifestyleTypes')->name('lifestyle.types');
Route::get('edit-lifestyle', 'GamesManagementController@editLifestyleType')->name('lifestyle.edit');
Route::get('create-lifestyle', 'GamesManagementController@createLifestyle')->name('lifestyle.create');
Route::get('games-present', 'GamesManagementController@lifestyleGamesPresent')->name('lifestylegames.index');
Route::get('create-lifestyle-game', 'GamesManagementController@createLifestyleGame')->name('lifestylegames.create');
Route::get('edit-lifestyle-game', 'GamesManagementController@editLifestyleGame')->name('lifestylegames.edit');
Route::get('view-lifestyle-game', 'GamesManagementController@showLifestyleGame')->name('lifestylegames.show');
 
//Route::get('/lifestyle','GamesManagementController@lifestyle');
Route::get('/lottery','GamesManagementController@lottery');
Route::get('/marketting','GamesManagementController@marketting');
Route::get('listpolls', 'Backend\ElectionsController@view');
Route::get('poll-details', 'Backend\ElectionsController@getinvidualpoll')->name("polls.details");
Route::get('poll-participants', 'Backend\ElectionsController@getparticipants')->name("polls.participants");
Route::get('listpolls', 'GamesManagementController@getAllPolls');
Route::get('poll-details', 'GamesManagementController@getPollDetails');
Route::post('/postemails','API\MarketingController@postemails');
Route::post('/postsms','API\MarketingController@postsms');
Route::post('createproject', 'API\ProjectsController@createproject');
Route::get('getprojects', 'API\ProjectsController@getprojects');
Route::get('getdetails', 'API\ProjectsController@getprojectsdetails');
Route::get('getstatistics', 'API\UssdController@getstatistics');
Route::get('getsessions', 'API\UssdController@getsessions');
Route::get('getsmstype', 'API\ProjectsController@getsmstype');
Route::get('getstatisticsms', 'API\SmsController@getstatistics');
Route::get('getoutgoing', 'API\SmsController@getoutgoing');
Route::get('getincomingsms', 'API\SmsController@getincomingsms');


/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| These routes deal with all authentication logic of the app. 
|
*/

Auth::routes();
Route::namespace('Auth')->group(function () {
	Route::get('register/verify/{token}', 'RegisterController@verifyEmail');
	Route::post('complete-registration', 'RegisterController@completeRegistration')->name('reg.complete');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    //
}

app/Http/Controllers/Backend/PermissionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;

class PermissionController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::orderBy('id', 'asc')->paginate(10);
        return view('backend/modules/permission/index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend/modules/permission/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|alpha_dash|unique:permissions,name',
            'display_name' => 'required|min:5|max:100',
            'description' => 'required|min:5|max:255'
        ]);

        $permission = new Permission;
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();

        Session::flash('new-permission', 'You have successfully created the '. $permission->name . ' permission');
        return redirect()->route('permissions.show', $permission->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $permission = Permission::findOrFail($id);
        $users = User::wherePermissionIs($permission->name)->paginate(10);
        return view('backend/modules/permission/show', compact('permission', 'users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::findOrFail($id);
        return view('backend/modules/permission/edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);

        $this->validate($request, [
            'name' => [
                'required', 'alpha_dash', 
                Rule::unique('permissions')->ignore($permission->id),
            ],
            'display_name' => 'required|min:5|max:100',
            'description' => 'required|min:5|max:255'
        ]);

        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
        
        Session::flash('update-permission', 'You have successfully updated the '. $permission->name . ' permission');
        return redirect()->route('permissions.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::findOrFail($id); // Pull back a given permission
        // Regular Delete
        $permission->delete(); // This will work no matter what

        Session::flash('delete-permission', 'The permission has been deleted successfully');
        return redirect()->route('permissions.index');
    }
}

resources/views/backend/modules/permission/create.blade.php
@extends('backend/layouts/template')

@section('title')
	Create Permission
@endsection

@push('dashboard-styles')
    <link href="{{ asset('css/iCheck/custom.css') }}" rel="stylesheet">
@endpush

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Create Permission</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li>
                    <a href="{{ route('permissions.index') }}">Permissions</a>
                </li>
                <li>
                    <strong>Create permission</strong>
                </li>

            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="ibox-float-e-margins">
                <div class="ibox-title">
                    <h5>Create new permission</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r">
                            <form action="{{ route('permissions.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label>Name</label> 
                                    <input type="text" placeholder="eg create-users" id="name" name="name" class="form-control">
                                    <!-- If name has error -->
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                                    <label>Display Name</label> 
                                    <input type="text" placeholder="eg Create Users" id="display_name" name="display_name" class="form-control">
                                    <!-- If display name has error -->
                                    @if ($errors->has('display_name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('display_name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                    <label>Description</label> 
                                    <input type="description" placeholder="eg Allows user to create other users" id="description" name="description" class="form-control">
                                    <!-- If description has error -->
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
@endsection

resources/views/backend/modules/permission/edit.blade.php
@extends('backend/layouts/template')

@section('title')
	Edit Permission
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Edit Permission</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Acces Control</a>
                </li>
                <li>
                    <a href="{{ route('permissions.index') }}">Permissions</a>
                </li>
                <li>
                    <strong>Edit {{ $permission->name }} permission</strong>
                </li>

            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="ibox-float-e-margins">
                <div class="ibox-title">
                    <h5>{{ $permission->name }} details</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r">
                            <form action="{{ route('permissions.update', $permission->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label>Name</label> 
                                    <input type="text" id="name" name="name" class="form-control" value="{{ $permission->name }}">
                                    <!-- If name has error -->
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }}">
                                    <label>Display Name</label> 
                                    <input type="text" id="display_name" name="display_name" class="form-control" value="{{ $permission->display_name }}">
                                    <!-- If display name has error -->
                                    @if ($errors->has('display_name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('display_name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                    <label>Description</label> 
                                    <input type="description" id="description" name="description" class="form-control" value="{{ $permission->description }}">
                                    <!-- If description has error -->
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
@endsection

resources/views/backend/modules/permission/index.blade.php
@extends('backend/layouts/template')

@section('title')
	All Permissions
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>All Permissions</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li class="active">
                    <strong>Permissions</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-float e-margins">
                <div class="ibox-title">
                    <h5>All permissions in {{ config('app.name') }}</h5>
                    <div class="ibox-tools"> 
                        <a href="{{ route('permissions.create') }}" class="btn btn-primary btn-sm">New Permission</a>
                    </div>
                </div>
            </div>

            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover users-table">
                        <thead>
                            <tr>
                                <th>Permission ID</th>
                                <th>Name</th>
                                <th>Display Name</th>
                                <th>Description</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($permissions) > 0)
                                @foreach($permissions as $permission)
                                    <tr>
                                        <td>{{ $permission->id }}</td>
                                        <td>{{ $permission->name }}</td>
                                        <td>{{ $permission->display_name }}</td>
                                        <td>{{ $permission->description }}</td>
                                        <td>
                                            {{ date('M j, Y', strtotime($permission->created_at)) . ' at ' . date('H:i', strtotime($permission->created_at)) }}
                                        </td>
                                        <td>
                                            <a href="{{ route('permissions.show', $permission->id) }}" class="btn btn-xs btn-primary" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                            <a href="{{ route('permissions.edit', $permission->id) }}" class="btn btn-xs btn-success" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                            {!! Form::open(['route' => ['permissions.destroy', $permission->id], 'method' => 'DELETE', 'style' => 'display: inline-block']) !!}                                
                                               {{Form::button('<i class="fa fa-trash"></i>', array('type' => 'submit', 'class' => 'btn btn-xs btn-danger', 'title' => 'Delete'))}}
                                            {!! Form::close() !!} &nbsp;&nbsp;
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6" class="alert alert-warning text-center">No permissions are available at the moment</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                    @if(count($permissions) > 0)
                        <div>
                            <span style="line-height: 60px;">Showing {!! $permissions->firstItem() !!} to {!! $permissions->lastItem() !!} of {{ $permissions->total() }} permissions</span>
                            <span class="pull-right">{!! $permissions->links(); !!}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/permission/show.blade.php
@extends('backend/layouts/template')

@section('title')
	View Permission
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>View Permission</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">Access Control</a>
                </li>
                <li>
                    <a href="{{ route('permissions.index') }}">Permissions</a>
                </li>
                <li>
                    <strong>View {{ $permission->name }} permission</strong>
                </li>

            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-4">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>About {{ $permission->name }} permission</h5>
                </div>
                <div class="ibox-content profile-content">
                    <h5>Description</h5>
                    <p class="text-justify">{{ $permission->description }}</p>
                    <div class="row m-t-lg">
                        <div class="col-md-6">
                            <i class="fa fa-sticky-note" style="color: #1BB394"></i>
                            <h5>Full name <strong>{{ ucfirst($permission->display_name) }}</strong></h5>
                        </div>
                        <div class="col-md-6">
                            <i class="fa fa-calendar" style="color: #1BB394"></i>
                            <h5>Created on <strong>{{ date('M j, Y', strtotime($permission->created_at)) }}</strong></h5>
                        </div>
                    </div>
                    <div class="user-button">
                        <a href="{{ route('permissions.edit', $permission->id) }}" class="btn btn-primary btn-sm btn-block"><i class="fa fa-pencil"></i> Edit Permission</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Users with this permission</h5>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>User ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Active</th>
                                    <th>View User</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                @if(count($users) > 0)
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{ $user->id }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>
                                                @if($user->active)
                                                    <span class="label label-primary">Active</span>
                                                @else
                                                    <span class="label label-danger">Inactive</span>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('users.show', $user->id) }}" class="btn btn-xs btn-primary" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td class="alert alert-warning text-center" colspan="5">No users with this permission are available</td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                        @if(count($users) > 0)
                            <div>
                                <span style="line-height: 60px;">Showing {!! $users->firstItem() !!} to {!! $users->lastItem() !!} of {{ $users->total() }} users</span>
                                <span class="pull-right">{!! $users->links(); !!}</span>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>    
    </div>
@endsection