routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
| These routes point to the public pages of the application. No 
| middleware is assigned to them as a result
|
*/

Route::namespace('Frontend')->group(function () {
	Route::get('/', 'PageController@getWelcome');
	Route::get('/documentation', 'PageController@getDocs');
	Route::get('complete-registration', 'PageController@getCompleteRegistration')->name('registration.complete');
	Route::get('login-and-signup-procedure', 'PageController@getHowTo')->name('howto');
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| These routes point to the private pages of the application. Some 
| middleware is assigned to them as a result.
|
*/

Route::namespace('Backend')->group(function () {
	Route::get('/dashboard', 'PageController@getDashboard')->name('dashboard');
	Route::get('ussd-static', 'PageController@getStaticUSSD')->name('ussd.static');
	Route::get('ussd-dynamic', 'PageController@getDynamicUSSD')->name('ussd.dynamic');
	Route::get('sms-static', 'PageController@getStaticSMS')->name('sms.static');
	Route::get('sms-dynamic', 'PageController@getDynamicSMS')->name('sms.dynamic');
	Route::get('shortcode-details', 'PageController@getShortcodeDetails')->name('details.shortcode');
	Route::resource('users', 'UserController');
	Route::get('verified', 'UserController@verified')->name('verified');
	Route::get('unverified', 'UserController@unverified')->name('unverified');
	Route::get('active', 'UserController@active')->name('active');
	Route::get('inactive', 'UserController@inactive')->name('inactive');
	Route::get('change-role/{id}', 'UserController@getChangeRole')->name('user.role');
	Route::post('change-role/{id}', 'UserController@postChangeRole')->name('role.change');
	Route::post('deactivate-user/{id}', 'UserController@deactivate')->name('user.deactivate');
	Route::post('activate-user/{id}', 'UserController@activate')->name('user.activate');
	Route::get('profile', 'PageController@getProfile')->name('user.profile');
	Route::post('change-avatar', 'PageController@postChangeAvatar')->name('avatar.change');
	Route::post('edit-details', 'PageController@postChangeDetails')->name('profile.update');
	Route::resource('roles', 'RoleController');
	Route::get('attach-permission/{id}', 'RoleController@getChangePermission')->name('role.permission');
	Route::post('attach-permission/{id}', 'RoleController@postChangePermission')->name('permission.change');
	Route::resource('permissions', 'PermissionController');
	Route::get('analytics-graphs', 'ReportController@getGraphs')->name('analytics.graphs');
	Route::get('analytics-reports', 'ReportController@getReports')->name('analytics.reports');
	Route::resource('companies', 'CompanyController');
	Route::post('activate-company/{id}', 'CompanyController@activateCompany')->name('company.activate');
	Route::post('deactivate-company/{id}', 'CompanyController@deactivateCompany')->name('company.deactivate');
	//Route::get('company-users', 'CompanyController@users')->name('company.users');
	Route::get('manage-company', 'CompanyController@manageCompany')->name('company.manage');
    Route::post('/createtrivia','GamesController@addtrivia')->name('trivia.create');
    Route::post('/addquestions','GamesController@addtriviaquestions')->name('trivia.addquestions');
    Route::get('/deletetrivia','GamesController@deletetrivia')->name('trivia.delete');
    Route::get('/marketing/email','MarketingController@emailMarketing')->name('marketingemail.send');
    Route::post('/marketing/email', 'MarketingController@postSendEmail')->name('marketingemail.bulksend');
	Route::get('marketing/email-groups', 'MarketingController@emailGroups')->name('marketingemail.groups');
	Route::get('marketing/view-email-group/{id}', 'MarketingController@showEmailGroup')->name('marketingemail.showgroup');
	Route::get('marketing/edit-email-group/{id}', 'MarketingController@editEmailGroup')->name('marketingemail.editgroup');
	Route::post('marketing/update-email-group/{id}', 'MarketingController@updateEmailGroup')->name('marketingemail.updategroup');
	Route::get('/marketing/view-email-contact/{id}','MarketingController@showEmailContact')->name('marketingemail.emailcontact');
	Route::post('add-email-group', 'MarketingController@addEmailGroup')->name('emailgroup.add');
	Route::post('add-email-contact/{id}', 'MarketingController@addEmailContact')->name('emailcontact.add');
	Route::get('marketing/sms', 'MarketingController@smsMarketing')->name('marketingsms.send');
	Route::get('marketing/sms-groups', 'MarketingController@smsGroups')->name('marketingsms.groups');
	Route::get('marketing/view-sms-group', 'MarketingController@showSMSGroup')->name('marketingsms.showgroup');
	Route::get('marketing/edit-sms-group', 'MarketingController@editSMSGroup')->name('marketingsms.editgroup');
	Route::get('/marketing/view-sms-contact','MarketingController@showSMSContact')->name('marketingsms.smscontact');
});

Route::get('/trivia','GamesManagementController@trivia');

Route::get('/listtrivia','GamesManagementController@listtrivia');
Route::get('/viewtrivia','GamesManagementController@viewtrivia');
Route::get('players','GamesManagementController@getPlayers');
Route::get('player-details', 'GamesManagementController@getPlayerDetails');
Route::get('/polls','GamesManagementController@polls')->name('polls');
Route::post('/create_polls','Backend\ElectionsController@create');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('/polls','GamesManagementController@polls');
Route::get('edit-poll', 'GamesManagementController@editPoll');
Route::get('lifestyle','GamesManagementController@lifestyle')->name('lifestyle.add_participants');
Route::get('lifestyle-types', 'GamesManagementController@getLifestyleTypes')->name('lifestyle.types');
Route::get('edit-lifestyle', 'GamesManagementController@editLifestyleType')->name('lifestyle.edit');
Route::get('create-lifestyle', 'GamesManagementController@createLifestyle')->name('lifestyle.create');
Route::get('games-present', 'GamesManagementController@lifestyleGamesPresent')->name('lifestylegames.index');
Route::get('create-lifestyle-game', 'GamesManagementController@createLifestyleGame')->name('lifestylegames.create');
Route::get('edit-lifestyle-game', 'GamesManagementController@editLifestyleGame')->name('lifestylegames.edit');
Route::get('view-lifestyle-game', 'GamesManagementController@showLifestyleGame')->name('lifestylegames.show');
 
//Route::get('/lifestyle','GamesManagementController@lifestyle');
Route::get('/lottery','GamesManagementController@lottery');
Route::get('/marketting','GamesManagementController@marketting');
Route::get('listpolls', 'Backend\ElectionsController@view');
Route::get('poll-details', 'Backend\ElectionsController@getinvidualpoll')->name("polls.details");
Route::get('poll-participants', 'Backend\ElectionsController@getparticipants')->name("polls.participants");
Route::get('listpolls', 'GamesManagementController@getAllPolls');
Route::get('poll-details', 'GamesManagementController@getPollDetails');
Route::post('/postemails','API\MarketingController@postemails');
Route::post('/postsms','API\MarketingController@postsms');
Route::post('createproject', 'API\ProjectsController@createproject');
Route::get('getprojects', 'API\ProjectsController@getprojects');
Route::get('getdetails', 'API\ProjectsController@getprojectsdetails');
Route::get('getstatistics', 'API\UssdController@getstatistics');
Route::get('getsessions', 'API\UssdController@getsessions');
Route::get('getsmstype', 'API\ProjectsController@getsmstype');
Route::get('getstatisticsms', 'API\SmsController@getstatistics');
Route::get('getoutgoing', 'API\SmsController@getoutgoing');
Route::get('getincomingsms', 'API\SmsController@getincomingsms');


/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| These routes deal with all authentication logic of the app. 
|
*/

Auth::routes();
Route::namespace('Auth')->group(function () {
	Route::get('register/verify/{token}', 'RegisterController@verifyEmail');
	Route::post('complete-registration', 'RegisterController@completeRegistration')->name('reg.complete');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'address', 'telephone'];

    public function users()
    {
    	return $this->hasMany('App\User');
    }
}

app/Http/Controllers/Backend/CompanyController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Company;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Auth;
use DB;
use App\User;
use App\Role;

class CompanyController extends Controller
{

    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin|executive');
        $this->middleware('role:admin')->only('index', 'activateCompany', 'deactivateCompany', 'show');
        $this->middleware('role:executive')->only('create', 'store', 'edit', 'update', 'destroy', 'manageCompany');

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = $request->user();

        $companies = Company::orderBy('id', 'asc')->paginate(10);    
        return view('backend/modules/company/index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $myCompany = DB::table('companies')->where('owner_id', $user->id)->first();

        if (empty($myCompany)) {
            return view('backend/modules/company/create', compact('user'));
        } else {
            Session::flash('company-exists', 'You already own a company! You can only edit and update but not add a new one');
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = $request->user();
        $myCompany = DB::table('companies')->where('owner_id', $user->id)->first();

        if (empty($myCompany)) {
             $request->validate([
                'name' => 'required|string|max:255|unique:companies,name',
                'address' => 'required|string|max:255',
                'telephone' => ['required','regex:/(07)[0-9]{8}/'],
            ]);

            $company = new Company;
            $company->name = $request->name;
            $company->address = $request->address;
            $company->telephone = $request->telephone;
            $company->owner_id = $user->id;

            $company->save();

            $user->company_id = $company->id;
            $user->active = true;
            $user->save();


            // Delete the default guest role
            DB::table('role_user')->where('user_id',$user->id)->delete();

            // Attach guest role
            $user->attachRole(Role::where('name','executive')->first());

            Session::flash('company-added', 'Company was added successfully. You are now an executive but your company is due activation');
            return redirect()->route('dashboard');
        } else {
            Session::flash('company-exists', 'You already own a company! You can only edit and update it but not add a new one');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::user();
        $company = Company::findOrFail($id);

        $users = User::where('company_id', '=', $company->id)->get();

        return view('backend/modules/company/show', compact('company', 'user', 'users'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //$company = Company::find($id);
        $user = Auth::user();
        $company = Company::where('owner_id', $user->id)->first();

        if ($company->status) {
           if (Gate::allows('is-my-company', $company)) {
                // Validate the request...
                $this->validate($request, [
                     'name' => [
                            'required', 'string', 'max:255', 
                            Rule::unique('companies')->ignore($company->id),
                        ],
                    'address' => 'required|string|max:255',
                    'telephone' => ['required','regex:/(07)[0-9]{8}/'],
                ]);
                
                $company->name = $request->name;
                $company->address = $request->address;
                $company->telephone = $request->telephone;
                $company->owner_id = Auth::user()->id;

                //save into DB
                $company->save();
                
                //Flash Message
                Session::flash('update-company', 'This company has been updated successfully!');

                // Redirect to view the company with saved changes
                return redirect()->route('company.manage', compact('company'));
            } else {
                Session::flash('not-permitted', 'You are not allowed to perform this operation');
                return redirect()->back();
            }
        } else {
            Session::flash('unapproved', 'You can only perform this operation after your company is approved');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        if ($company->status) {
            if (Gate::allows('is-my-company', $company)) {
                $company->delete();
                Session::flash('company-deleted', 'You have successfully deleted this company');
                return redirect()->back();
            } else {
                Session::flash('not-permitted', 'You are not allowed to perform this operation');
                return redirect()->back();
            }
        } else {
            Session::flash('unapproved', 'You can only perform this operation after your company is approved');
            return redirect()->back();
        }
    }

    /**
     * Activate company 
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function activateCompany($id)
    {
        $company = Company::findOrFail($id);

        DB::table('companies')->where('id', $company->id)->update(['status' => true]);

        //Send Company Owner Email
        

        Session::flash('company-activated', 'Company has been activated successfully');
        return redirect()->route('companies.index');
    }

    /**
     * Deactivate company 
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function deactivateCompany($id)
    {
        $company = Company::findOrFail($id);

        DB::table('companies')->where('id', $company->id)->update(['status' => false]);

        //Send Company Owner Email
        

        Session::flash('company-deactivated', 'Company has been deactivated successfully');
        return redirect()->route('companies.index');
    }

    /**
     *
     * Show view for managing one's company
     *
     */
    public function manageCompany()
    {
        $user = Auth::user();
        $company = DB::table('companies')->where('owner_id', $user->id)->first();
        if (!empty($company)) {
            $users = User::where('company_id', '=', $company->id)->paginate(10);
        } else {
            Session::flash('company-first', 'You can only access this page after adding your company');
            return redirect()->back();
        }

        return view('backend/modules/company/manage', compact('company', 'users'));
    }
}

resources/views/backend/modules/company/create.blade.php
@extends('backend/layouts/template')

@section('title')
	Add Company
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Add Company</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="{{ route('companies.index') }}">Companies</a>
                </li>
                <li class="active">
                    <strong>Add Company</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Add Company</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r">
                            <form action="{{ route('companies.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label>Name</label> 
                                    <input type="text" placeholder="Company name" id="name" name="name" class="form-control">
                                    <!-- If password has error -->
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                    <label>Address</label> 
                                    <input type="text" placeholder="Company address" id="address" name="address" class="form-control">
                                    <!-- If password has error -->
                                    @if ($errors->has('address'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('address') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('telephone') ? ' has-error' : '' }}">
                                    <label>Telephone</label> 
                                    <input type="text" placeholder="Company telephone" id="telephone" name="telephone" class="form-control">
                                    <!-- If password has error -->
                                    @if ($errors->has('telephone'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('telephone') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary btn-block">Add</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/company/edit.blade.php
@extends('backend/layouts/template')

@section('title')
	Edit Company
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Edit Company</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li>
                    <a href="{{ route('companies.index') }}">Companies</a>
                </li>
                <li class="active">
                    <strong>Edit Company</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit Company</h5>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r">
                            <form action="{{ route('companies.update', $company->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label>Name</label> 
                                    <input type="text" placeholder="Company name" id="name" name="name" class="form-control" value="{{ $company->name }}">
                                    <!-- If password has error -->
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                    <label>Address</label> 
                                    <input type="text" placeholder="Company address" id="address" name="address" class="form-control" value="{{ $company->address }}">
                                    <!-- If password has error -->
                                    @if ($errors->has('address'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('address') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('telephone') ? ' has-error' : '' }}">
                                    <label>Telephone</label> 
                                    <input type="text" placeholder="Company telephone" id="telephone" name="telephone" class="form-control" value="{{ $company->telephone }}">
                                    <!-- If password has error -->
                                    @if ($errors->has('telephone'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('telephone') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-primary btn-block">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/modules/company/index.blade.php
@extends('backend/layouts/template')

@section('title')
	All Companies
@endsection

@section('page-header')
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>All Companies</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard') }}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>Companies</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover users-table">
                        @include('backend/modules/company/partials/_thead')
                        <tbody>
                            @if(count($companies) > 0)
                                @foreach($companies as $company)
                                    <tr>
                                        <td>{{ $company->name }}</td>
                                        <td>{{ $company->address }}</td>
                                        <td>{{ $company->telephone }}</td>
                                        <td>
                                            @if($company->status)
                                                <span class="label label-primary">Active</span>
                                            @else
                                                <span class="label label-danger">Inactive</span>
                                            @endif
                                        </td>
                                        <td>
                                            {{ date('M j, Y', strtotime($company->created_at)) . ' at ' . date('H:i', strtotime($company->created_at)) }}
                                        </td>
                                        <td>
                                            <a href="{{ route('companies.show', $company->id) }}" class="btn btn-xs btn-primary" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                            @if(Auth::user()->hasRole('admin'))
                                                @if($company->status)
                                                    {!! Form::open(['route' => ['company.deactivate', $company->id], 'method' => 'POST', 'style' => 'display: inline-block']) !!}                                
                                                       {{Form::button('<i class="fa fa-ban"></i>', array('type' => 'submit', 'class' => 'btn btn-xs btn-warning', 'title' => 'Deactivate'))}}
                                                    {!! Form::close() !!} &nbsp;&nbsp;
                                                @else
                                                    {!! Form::open(['route' => ['company.activate', $company->id], 'method' => 'POST', 'style' => 'display: inline-block']) !!}                                
                                                       {{Form::button('<i class="fa fa-check"></i>', array('type' => 'submit', 'class' => 'btn btn-xs btn-primary', 'title' => 'Activate'))}}
                                                    {!! Form::close() !!} &nbsp;&nbsp;
                                                @endif
                                            @else
                                                <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-xs btn-success" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp; &nbsp;
                                                {!! Form::open(['route' => ['companies.destroy', $company->id], 'method' => 'DELETE', 'style' => 'display: inline-block']) !!}                                
                                                   {{Form::button('<i class="fa fa-trash"></i>', array('type' => 'submit', 'class' => 'btn btn-xs btn-danger', 'title' => 'Delete'))}}
                                                {!! Form::close() !!} &nbsp;&nbsp;
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="6" class="alert alert-warning text-center">
                                        @if(Auth::user()->hasRole('executive'))
                                            You have no companies
                                        @else
                                            There are no companies available
                                        @endif
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                    @if(count($companies) > 0)
                        <div>
                            <span style="line-height: 60px;">Showing {!! $companies->firstItem() !!} to {!! $companies->lastItem() !!} of {{ $companies->total() }} companies</span>
                            <span class="pull-right">{!! $companies->links(); !!}</span>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection